name: Deploy backend

on:
  push:
    branches: [main]
    paths:
      - packages/backend/**
      - packages/shared/**
      - package.json
      - package-lock.json
      - fly.toml
      - .github/workflows/deploy-backend.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-backend
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
